Vagrant.configure("2") do |config|
    config.vm.provider "vmware_fusion" do |v|
      v.vmx["memsize"] = "2048" # Set memory size for VMs
      v.vmx["numvcpus"] = "2"   # Set number of CPUs for VMs
      v.gui = true 
    end
  
    # Create Kubernetes VMs
    (1..3).each do |i| # Create 3 master nodes
      config.vm.define "master#{i}" do |node|
        node.vm.box = "generic/ubuntu2004"
        node.vm.hostname = "master#{i}"
      end
    end
  
    (1..2).each do |i| # Create 2 worker nodes
      config.vm.define "worker#{i}" do |node|
        node.vm.box = "generic/ubuntu2004"
        node.vm.hostname = "worker#{i}"
      end
    end
  end
  